# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'crickrivals-2.0.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sqlite3
"""from PyQt5 import QtCore, QtGui, QtWidgets
 # update if the class name is different

from PyQt5.QtWidgets import QLabel
from PyQt5.QtCore import QTimer"""

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QLabel, QMainWindow, QVBoxLayout, QGridLayout, QWidget, QScrollArea, QFrame, QPushButton
from PyQt5.QtCore import QTimer
from createDashboard import Ui_MainWindow as Ui_Dashboard

class MarqueeLabel(QLabel):
    def __init__(self, text="", parent=None):
        super().__init__(text, parent)
        self.original_text = text + "     "
        self.index = 0
        self.timer = QTimer(self)
        self.timer.timeout.connect(self.scroll_text)
        self.timer.start(200)

    def scroll_text(self):
        self.index = (self.index + 1) % len(self.original_text)
        scroll_text = self.original_text[self.index:] + self.original_text[:self.index]
        self.setText(scroll_text)


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1720, 910)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        # Scroll Area
        self.scrollArea = QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(10, 10, 1700, 855))
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")

        # Scroll Area Contents with Layout
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(20)

        # Marquee Label
        self.label_2 = MarqueeLabel("WELCOME TO CRICKRIVALS 2.0")
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setStyleSheet("color: white; background-color: black; border-radius: 10px;")
        self.verticalLayout.addWidget(self.label_2)

        # Horizontal Line
        self.line = QFrame()
        self.line.setFrameShape(QFrame.HLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.verticalLayout.addWidget(self.line)

        # Grid Layout Widget
        self.gridLayoutWidget = QWidget()
        self.gridLayout = QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)

        # Team Logos & Labels
        self.label = QLabel()
        self.label.setPixmap(QtGui.QPixmap("images/pbks.png"))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.gridLayout.addWidget(self.label, 0, 0)

        self.label_5 = QLabel("VS")
        font_label = QtGui.QFont()
        font_label.setPointSize(20)
        font_label.setBold(True)
        self.label_5.setFont(font_label)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.gridLayout.addWidget(self.label_5, 0, 1)

        self.label_6 = QLabel()
        self.label_6.setPixmap(QtGui.QPixmap("images/rcb.png"))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.gridLayout.addWidget(self.label_6, 0, 2)

        self.pushButton = QPushButton("Manage PBKS Team")
        self.gridLayout.addWidget(self.pushButton, 1, 2)

        self.line_2 = QFrame()
        self.line_2.setFrameShape(QFrame.HLine)
        self.line_2.setFrameShadow(QFrame.Sunken)
        self.gridLayout.addWidget(self.line_2, 2, 0, 1, 3)

        self.label_3 = QLabel()
        self.label_3.setPixmap(QtGui.QPixmap("images/csk.png"))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.gridLayout.addWidget(self.label_3, 3, 0)

        self.label_7 = QLabel("VS")
        self.label_7.setFont(font_label)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.gridLayout.addWidget(self.label_7, 3, 1)

        self.label_8 = QLabel()
        self.label_8.setPixmap(QtGui.QPixmap("images/mi.png"))
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.gridLayout.addWidget(self.label_8, 3, 2)

        self.pushButton_2 = QPushButton("Manage MI Team")
        self.gridLayout.addWidget(self.pushButton_2, 4, 2)

        self.line_3 = QFrame()
        self.line_3.setFrameShape(QFrame.HLine)
        self.line_3.setFrameShadow(QFrame.Sunken)
        self.gridLayout.addWidget(self.line_3, 5, 0, 1, 3)

        self.label_4 = QLabel()
        self.label_4.setPixmap(QtGui.QPixmap("images/lsg.png"))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.gridLayout.addWidget(self.label_4, 6, 0)

        self.label_9 = QLabel("VS")
        self.label_9.setFont(font_label)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.gridLayout.addWidget(self.label_9, 6, 1)

        self.label_10 = QLabel()
        self.label_10.setPixmap(QtGui.QPixmap("images/srh.png"))
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.gridLayout.addWidget(self.label_10, 6, 2)

        self.pushButton_3 = QPushButton("Manage RCB Team")
        self.gridLayout.addWidget(self.pushButton_3, 7, 2)

        # Add Grid Layout to Main Vertical Layout
        self.verticalLayout.addWidget(self.gridLayoutWidget)

        # Add a stretch at the end so content doesn't crowd bottom
        self.verticalLayout.addStretch()

        # Set scroll area widget
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        # Set Central Widget
        MainWindow.setCentralWidget(self.centralwidget)

        # Menu Bar
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1720, 22))
        MainWindow.setMenuBar(self.menubar)

        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")

        # Status Bar
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        MainWindow.setStatusBar(self.statusbar)

        # Menu Actions
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setText("New")

        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setText("Save")

        self.actionmanage_team = QtWidgets.QAction(MainWindow)
        self.actionmanage_team.setText("Manage Team")

        self.actionInstructions = QtWidgets.QAction(MainWindow)
        self.actionInstructions.setText("Instructions")

        self.actionManual = QtWidgets.QAction(MainWindow)
        self.actionManual.setText("Manual")

        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionmanage_team)
        self.menuHelp.addAction(self.actionInstructions)
        self.menuHelp.addAction(self.actionManual)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.team_name_map = {
            "pbks.png": "Punjab Kings (PBKS)",
            "rcb.png": "Royal Challengers Bengaluru (RCB)",
            "csk.png": "Chennai Super Kings (CSK)",
            "mi.png": "Mumbai Indians (MI)",
            "srh.png": "Sunrisers Hyderabad (SRH)",
            "gt.png": "Gujarat Titans (GT)",
            "dc.png": "Delhi Capitals (DC)",
            "kkr.png": "Kolkata Knight Riders (KKR)",
            "rr.png": "Rajasthan Royals (RR)",
            "lsg.png": "Lucknow Super Giants (LSG)",
        }

        self.actionNew.triggered.connect(lambda: self.open_dashboard(0))
        self.pushButton.clicked.connect(lambda: self.open_dashboard(1))
        self.pushButton_2.clicked.connect(lambda: self.open_dashboard(2))
        self.pushButton_3.clicked.connect(lambda: self.open_dashboard(3))
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.scrollArea, self.pushButton)
        MainWindow.setTabOrder(self.pushButton, self.pushButton_2)
        MainWindow.setTabOrder(self.pushButton_2, self.pushButton_3)
    
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CrickRivals 2.0"))
        self.label_2.setText(_translate("MainWindow", "WELCOME TO CRICKRIVALS 2.0")) 
        self.label_7.setText(_translate("MainWindow", "VS"))
        self.pushButton_3.setText(_translate("MainWindow", "Enter Contest"))
        self.pushButton_2.setText(_translate("MainWindow", "Enter Contest"))
        self.label_5.setText(_translate("MainWindow", "VS"))
        self.pushButton.setText(_translate("MainWindow", "Enter Contest"))
        self.label_9.setText(_translate("MainWindow", "VS"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionNew.setText(_translate("MainWindow", "New Team"))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionSave.setText(_translate("MainWindow", "Save Team"))
        self.actionmanage_team.setText(_translate("MainWindow", "Manage Team"))
        self.actionmanage_team.setShortcut(_translate("MainWindow", "Ctrl+M"))
        self.actionInstructions.setText(_translate("MainWindow", "Instructions"))
        self.actionManual.setText(_translate("MainWindow", "Manual"))

    def open_dashboard(self, row_num):
        self.dashboard_window = QtWidgets.QMainWindow()
        self.dashboard_ui = Ui_Dashboard(self.username)
        self.dashboard_ui.setupUi(self.dashboard_window)
        self.dashboard_window.setStyleSheet( """
QMainWindow {
    background-color: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #f5faff, stop:1 #e0f7ff);
    font-family: 'Segoe UI';
}

QLabel#label_banner, QLabel#vsLabel {
    background-color: #003366;
    color: white;
    font: bold 20px 'Segoe UI';
    padding: 12px;
    border-radius: 10px;
    qproperty-alignment: AlignCenter;
}

QFrame {
    background-color: #ffffff;
    border: 1px solid #b3d9ff;
    border-radius: 12px;
    padding: 8px;
}

QLabel[objectName^="teamLogo"] {
    border: 2px solid #3399ff;
    border-radius: 15px;
    padding: 8px;
    background-color: #f9f9f9;
}

QListWidget {
    background-color: #ffffff;
    border: 2px solid #99ccff;
    border-radius: 10px;
    padding: 10px;
    font-size: 14px;
}

QListWidget::item:selected {
    background-color: #b3e5ff;
    color: #00334d;
    border-radius: 6px;
}

QPushButton {
    background-color: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #00c6ff, stop:1 #0072ff);
    color: white;
    font: bold 14px 'Segoe UI';
    padding: 10px 20px;
    border-radius: 10px;
}

QPushButton:hover {
    background-color: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #33ccff, stop:1 #3399ff);
}

QPushButton:pressed {
    background-color: #005c99;
}

/* ✅ Combo Boxes */
QComboBox {
    background-color: #ffffff;
    border: 1px solid #b3d9ff;
    padding: 5px 10px;
    border-radius: 8px;
    font-weight: bold;
    color: #003366;
}

QComboBox:hover {
    background-color: #e0f2ff; /* Light blue on hover */
    border: 1px solid #66bfff;
}

QRadioButton {
    font-size: 13px;
    color: #004d66;
    padding: 4px;
}

QLabel {
    font-size: 14px;
    color: #00334d;
}
""")


        if row_num != 0:
            team1, team2 = self.get_teams_from_db(row_num)
            if not team1 or not team2:
                print("❌ No teams found for row", row_num)
                return
            self.dashboard_ui.preset_teams_in_combobox(team1, team2)

        self.dashboard_window.show()


    def get_teams_from_db(self, row_num):
        try:
            conn = sqlite3.connect('app_database.db')
            cursor = conn.cursor()

            # Step 1: Get team IDs using offset
            cursor.execute("SELECT team1, team2 FROM real_time_match LIMIT 1 OFFSET ?", (row_num - 1,))
            result = cursor.fetchone()

            if not result:
                return None, None

            team1_name, team2_name = result

            conn.close()

            return team1_name, team2_name

        except Exception as e:
            print("⚠️ DB Error in get_teams_from_db:", e)
            return None, None

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
